FROM python:3.11-slim

# ПРИНУДИТЕЛЬНАЯ ПЕРЕСБОРКА 2026-09-03

WORKDIR /app

COPY backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY backend/ .

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
